Packer base
Otus-DevOps-2021-05/apocatastasys_infra pull request #8
Opened 2021-06-27 18:01 UTC by apocatastasys

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-06-27 18:06 UTC, apocatastasys commented
Написан параметризированный шаблон packer для создания ВМ. 
Для запуска шаблона требуется:
1 - сделать экспорт переменных окружения:
$ export YC_SERVICE_ACCOUNT_KEY_FILE=/root/key.json
$ export YC_FOLDER=b1ggs1k8rekvikjdrr58

2 - запустить сборку командой: 
$ packer build -var-file=variables.json ubuntu16.json

2021-06-28 08:32 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. variables.json.examples нужно переименовать в variables.json.example. Ну и перепроверить тесты еще раз. ДЗ возвращаю на доработку, осталось немного =)

2021-06-28 15:07 UTC, apocatastasys commented
Добрый день, тест почему то ругается на : 
  +* a source_image_name or source_image_family must be specified
     +* a token or service account key file must be specified

2021-06-29 08:12 UTC, mrgreyves requested changes
Здравствуйте!) Вам стоит добавить фейковый ключ в репозиторий, тогда тесты заработают =)

2021-06-29 09:39 UTC, apocatastasys commented
Добрйы день, тесты прошли.

2021-06-30 19:47 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь все готово =)

2021-07-01 03:55 UTC, merged